### PR TITLE
Added testing utilities for noisegate

### PR DESCRIPTION
**Pull request by samhincks**
- audio-worklet/test/testharness.js is an exact copy of [testharness.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/resources/testharness.js?q=testharness.js&dr=C&l=2600) at 2017-08-02
- audio-worklet/test/audit.js is an exact copy of [audit.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/webaudio/resources/audit.js?q=audit.js&dr=C&l=39) at 2017-08-02
- audio-worklet/test/audit-util.js is an exact copy of [audit-util.js](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/webaudio/resources/audit-util.js?dr=C) at 2017-08-02

### CODE REVIEW

**Comment by hoch** [comment]
Please say what you're trying to do with this PR in the description. Few bullet points would be nice.

**Comment by hoch** [comment]
Are these exact copies from https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/webaudio/resources?

**Comment by samhincks** [comment]
Yes these are exact copies. I just double checked with a diff that none of the files have changed in the Chromium repository since I last copied them.

**Comment by hoch** [comment]
Then you can update the description with your last comment + a link to the source. Otherwise we'll have to look through the comment to figure out what this PR does.

**Comment by rtoy** [comment]
Also, when you do the merge, github asks for a merge message.  This should be filled out more completely so that when I do a git log the message makes some sense.

(And yes, I am really terrible at doing this with github merge.  I usually write pretty good messages for my local commits, but the merge messages I enter are terrible.  I need to do a better job of this too.)

**Pull request merged**
